#!/system/bin/sh
#  by daniel_hk (daniel.p6800@gmail.com)

LOG_TAG="ApkPermissions"
GOOGLE_PLAY_SERVICE=com.google.android.gms
SETUPWIZARD=com.google.android.setupwizard
DONE_FILE=/data/ApkPermissions_done

logi ()
{
  /system/bin/log -t ${LOG_TAG} -p i ": $@"
}

loge ()
{
  /system/bin/log -t ${LOG_TAG} -p e ": $@"
}

failed ()
{
  loge "$1: exit code $2"
  exit $2
}

grant_permission ()
{
  pm grant $1 $2

  case $? in
    0) logi "$1 granted $2";;
    *) failed "error granting $2" $?;;
  esac
}

# check if already done
if [ -f ${DONE_FILE} ]; then
  exit 0;
fi

# Google SetupWizard indicate Gapps installed
GAPPS=`pm list packages com.google.android | grep 'google.android'`
local count=0
while [ -z "${GAPPS}" ]
do
  count=$(($count+1))
  if [ $count -gt 10 ]; then
    # most likely from a dirty flash, consider done
    echo 1 > ${DONE_FILE}
    loge "time out getting pm list!"
    exit -1
  fi
  logi "wait for Package Manager to start"
  sleep 10
  GAPPS=`pm list packages com.google.android | grep 'google.android'`
done

GAPPS_EXIST=`echo ${GAPPS} | grep 'setupwizard'`

if [ -z "${GAPPS_EXIST}" ];
then
  logi "Gapps not insalled"
else
  grant_permission ${SETUPWIZARD} android.permission.READ_PRECISE_PHONE_STATE

  # Google Play Service
  grant_permission ${GOOGLE_PLAY_SERVICE} android.permission.ACCESS_FINE_LOCATION 
  grant_permission ${GOOGLE_PLAY_SERVICE} android.permission.ACCESS_COARSE_LOCATION

  # indicate done if success
  echo 1 > ${DONE_FILE}
fi

exit 0
